# Generated by Django 5.1 on 2024-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_cadastro_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='reset_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
