# Generated by Django 5.1 on 2024-11-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cadastro_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
